from correctionlib import _core

#Download the correct JSON files 
evaluator = _core.CorrectionSet.from_file('/home/bowerbird/Yash/Work/Jupytr/Scale_Factors/2016/post_VFP/Electron/electron.json')

#Reconstruction (pT< 20 GeV) Run-2 scale factor
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoBelow20",-2.2, 15.0)
print("Reco sf below 20 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoBelow20",-1.8, 15.0)
print("Reco sf below 20 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoBelow20",-1.510, 15.0)
print("Reco sf below 20 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoBelow20",-1.2, 15.0)
print("Reco sf below 20 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoBelow20",-0.5, 15.0)
print("Reco sf below 20 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoBelow20",0.5, 15.0)
print("Reco sf below 20 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoBelow20",1.2, 15.0)
print("Reco sf below 20 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoBelow20",1.51, 15.0)
print("Reco sf below 20 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoBelow20",1.8, 15.0)
print("Reco sf below 20 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoBelow20",2.2, 15.0)
print("Reco sf below 20 GeV is:"+str(valsf))

print("-------------------------------------------------------------------")
print("-------------------------------------------------------------------")
#Reconstruction (pT> 20 GeV && pT<45GeV) Run-2 scale factor
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-2.2, 25.0)
print("Reco sf above 20 GeV and less than 45 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-1.8, 25.0)
print("Reco sf above 20 GeV and less than 45 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-1.51, 25.0)
print("Reco sf above 20 GeV and less than 45 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-1.2, 25.0)
print("Reco sf above 20 GeV and less than 45 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-0.7, 25.0)
print("Reco sf above 20 GeV and less than 45 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-0.3, 25.0)
print("Reco sf above 20 GeV and less than 45 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",0.3, 25.0)
print("Reco sf above 20 GeV and less than 45 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",0.7, 25.0)
print("Reco sf above 20 GeV and less than 45 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",1.2, 25.0)
print("Reco sf above 20 GeV and less than 45 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",1.51, 25.0)
print("Reco sf above 20 GeV and less than 45 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",1.8, 25.0)
print("Reco sf above 20 GeV and less than 45 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",2.2, 25.0)
print("Reco sf above 20 GeV and less than 45 GeV is:"+str(valsf))
print("-------------------------------------------------------------------")
print("-------------------------------------------------------------------")
#Reconstruction (pT> 45 GeV && pT<75GeV) Run-2 scale factor
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-2.2, 50.0)
print("Reco sf above 45 GeV and less than 75 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-1.8, 50.0)
print("Reco sf above 45 GeV and less than 75 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-1.51, 50.0)
print("Reco sf above 45 GeV and less than 75 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-1.2, 50.0)
print("Reco sf above 45 GeV and less than 75 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-0.7, 50.0)
print("Reco sf above 45 GeV and less than 75 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-0.3, 50.0)
print("Reco sf above 45 GeV and less than 75 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",0.3, 50.0)
print("Reco sf above 45 GeV and less than 75 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",0.7, 50.0)
print("Reco sf above 45 GeV and less than 75 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",1.2, 50.0)
print("Reco sf above 45 GeV and less than 75 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",1.51, 50.0)
print("Reco sf above 45 GeV and less than 75 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",1.8, 50.0)
print("Reco sf above 45 GeV and less than 75 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",2.2, 50.0)
print("Reco sf above 45 GeV and less than 75 GeV is:"+str(valsf))
print("-------------------------------------------------------------------")
print("-------------------------------------------------------------------")
#Reconstruction (pT> 75 GeV && pT<100GeV) Run-2 scale factor
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-2.2, 90.0)
print("Reco sf above 75 GeV and less than 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-1.8, 90.0)
print("Reco sf above 75 GeV and less than 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-1.51, 90.0)
print("Reco sf above 75 GeV and less than 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-1.2, 90.0)
print("Reco sf above 75 GeV and less than 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-0.7, 90.0)
print("Reco sf above 75 GeV and less than 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-0.3, 90.0)
print("Reco sf above 75 GeV and less than 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",0.3, 90.0)
print("Reco sf above 75 GeV and less than 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",0.7, 90.0)
print("Reco sf above 75 GeV and less than 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",1.2, 90.0)
print("Reco sf above 75 GeV and less than 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",1.51, 90.0)
print("Reco sf above 75 GeV and less than 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",1.8, 90.0)
print("Reco sf above 75 GeV and less than 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",2.2, 90.0)
print("Reco sf above 75 GeV and less than 100 GeV is:"+str(valsf))
print("-------------------------------------------------------------------")
print("-------------------------------------------------------------------")
#Reconstruction (pT> 100 GeV && pT<1000GeV) Run-2 scale factor
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-2.2, 125.0)
print("Reco sf above 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-1.8, 125.0)
print("Reco sf above 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-1.51, 125.0)
print("Reco sf above 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-1.2, 125.0)
print("Reco sf above 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-0.7, 125.0)
print("Reco sf above 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",-0.3, 125.0)
print("Reco sf above 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",0.3, 125.0)
print("Reco sf above 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",0.7, 125.0)
print("Reco sf above 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",1.2, 125.0)
print("Reco sf above 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",1.51, 125.0)
print("Reco sf above 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",1.8, 125.0)
print("Reco sf above 100 GeV is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","RecoAbove20",2.2, 125.0)
print("Reco sf above 100 GeV is:"+str(valsf))
print("-------------------------------------------------------------------")
print("-------------------------------------------------------------------")
#ID/Iso Run-2 scale factor: pT<20
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-2.2, 15.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-1.8, 15.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-1.51,15.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-1.2, 15.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-0.3, 15.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",0.3, 15.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",1.2, 15.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",1.51,15.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",1.8, 15.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",2.2, 15.0)
print("Medium ID sf is:"+str(valsf))
print("-------------------------------------------------------------------")
print("-------------------------------------------------------------------")
#pT>20 & pT<35
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-2.2, 25.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-1.8, 25.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-1.51,25.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-1.2, 25.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-0.7, 25.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",0.7, 25.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",1.2, 25.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",1.51,25.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",1.8, 25.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",2.2, 25.0)
print("Medium ID sf is:"+str(valsf))
print("-------------------------------------------------------------------")
print("-------------------------------------------------------------------")
#pT>35 & pT<50
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-2.2, 45.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-1.8, 45.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-1.51,45.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-1.2, 45.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-0.7, 45.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",0.7, 45.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",1.2, 45.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",1.51,45.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",1.8, 45.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",2.2, 45.0)
print("Medium ID sf is:"+str(valsf))
print("-------------------------------------------------------------------")
print("-------------------------------------------------------------------")
#pT>50 & pT<100
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-2.2, 65.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-1.8, 65.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-1.51,65.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-1.2, 65.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-0.7, 65.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",0.7, 65.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",1.2, 65.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",1.51,65.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",1.8, 65.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",2.2, 65.0)
print("Medium ID sf is:"+str(valsf))
print("-------------------------------------------------------------------")
print("-------------------------------------------------------------------")
#pT>100 & pT<1000
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-2.2, 115.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-1.8, 115.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-1.51,115.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-1.2, 115.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",-0.7, 115.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",0.7, 115.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",1.2, 115.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",1.51,115.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",1.8, 115.0)
print("Medium ID sf is:"+str(valsf))
valsf= evaluator["UL-Electron-ID-SF"].evaluate("2016postVFP","sf","Medium",2.2, 115.0)
print("Medium ID sf is:"+str(valsf))
print("-------------------------------------------------------------------")
print("-------------------------------------------------------------------")
