from correctionlib import _core

#Download the correct JSON files 
evaluator = _core.CorrectionSet.from_file('/home/bowerbird/Yash/Work/Jupytr/Scale_Factors/2018/Muons/muon_Z.json')

# TrackerMuon Reconstruction UL scale factor
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 0.5, 18.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 0.5, 22.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 0.5, 28.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 0.5, 35.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 0.5, 45.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 0.5, 55.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 0.5, 65.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 0.5, 180.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
print("====================================================================================")
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 1.0, 18.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 1.0, 22.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 1.0, 28.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 1.0, 35.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 1.0, 45.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 1.0, 55.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 1.0, 65.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 1.0, 180.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
print("====================================================================================")
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 1.5, 18.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 1.5, 22.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 1.5, 28.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 1.5, 35.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 1.5, 45.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 1.5, 55.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 1.5, 65.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 1.5, 180.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
print("====================================================================================")
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 2.2, 18.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 2.2, 22.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 2.2, 28.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 2.2, 35.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 2.2, 45.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 2.2, 55.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 2.2, 65.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
valsf = evaluator["NUM_TrackerMuons_DEN_genTracks"].evaluate("2018_UL", 2.2, 180.0, "sf")
print("Tracker Muon reco sf is: " + str(valsf))
print("====================================================================================")

# Medium ID UL scale factor
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 0.5, 18.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 0.5, 22.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 0.5, 28.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 0.5, 35.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 0.5, 45.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 0.5, 55.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 0.5, 65.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 0.5, 180.0, "sf")
print("MediumID sf is: " + str(valsf))
print("====================================================================================")
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 1.0, 18.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 1.0, 22.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 1.0, 28.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 1.0, 35.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 1.0, 45.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 1.0, 55.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 1.0, 65.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 1.0, 180.0, "sf")
print("MediumID sf is: " + str(valsf))
print("====================================================================================")
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 1.5, 18.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 1.5, 22.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 1.5, 28.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 1.5, 35.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 1.5, 45.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 1.5, 55.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 1.5, 65.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 1.5, 180.0, "sf")
print("MediumID sf is: " + str(valsf))
print("====================================================================================")
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 2.2, 18.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 2.2, 22.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 2.2, 28.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 2.2, 35.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 2.2, 45.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 2.2, 55.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 2.2, 65.0, "sf")
print("MediumID sf is: " + str(valsf))
valsf = evaluator["NUM_MediumID_DEN_TrackerMuons"].evaluate("2018_UL", 2.2, 180.0, "sf")
print("MediumID sf is: " + str(valsf))
print("====================================================================================")

# Tight Iso UL scale factor
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 0.5, 18.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 0.5, 22.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 0.5, 28.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 0.5, 35.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 0.5, 45.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 0.5, 55.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 0.5, 65.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 0.5, 180.0, "sf")
print("Tight Iso sf is: " + str(valsf))
print("====================================================================================")
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 1.0, 18.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 1.0, 22.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 1.0, 28.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 1.0, 35.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 1.0, 45.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 1.0, 55.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 1.0, 65.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 1.0, 180.0, "sf")
print("Tight Iso sf is: " + str(valsf))
print("====================================================================================")
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 1.5, 18.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 1.5, 22.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 1.5, 28.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 1.5, 35.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 1.5, 45.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 1.5, 55.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 1.5, 65.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 1.5, 180.0, "sf")
print("Tight Iso sf is: " + str(valsf))
print("====================================================================================")
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 2.2, 18.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 2.2, 22.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 2.2, 28.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 2.2, 35.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 2.2, 45.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 2.2, 55.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018_UL", 2.2, 65.0, "sf")
print("Tight Iso sf is: " + str(valsf))
valsf = evaluator["NUM_TightRelIso_DEN_MediumID"].evaluate("2018", 2.2, 180.0, "sf")
print("Tight Iso sf is: " + str(valsf))
print("====================================================================================")



'''# Trigger UL systematic uncertainty only 
valsyst = evaluator["NUM_IsoMu24_or_IsoTkMu24_DEN_CutBasedIdTight_and_PFIsoTight"].evaluate("2016postVFP_UL", 1.8, 54.0, "syst")
print("syst is: " + str(valsyst))
'''
